UserService methods tests
aidian3k/software-testing-app pull request #2
Opened 2023-10-21 20:57 UTC by briocky

2023-10-21 21:27 UTC, aidian3k requested changes
Changes needed as we talked

2023-10-21 21:42 UTC, aidian3k reviewed
Better, but you should still make some changes

2023-10-21 21:42 UTC, aidian3k commented on src/test/java/project/eepw/softwaretestingcrud/domain/user/data/UserServiceTest.java
> +  }
what?

2023-10-21 21:42 UTC, aidian3k commented on src/test/java/project/eepw/softwaretestingcrud/domain/user/data/UserServiceTest.java
> +  private AutoCloseable closeable;
?

2023-10-21 21:42 UTC, aidian3k commented on src/test/java/project/eepw/softwaretestingcrud/domain/user/data/UserServiceTest.java
> +        .build();
extract all of these to some private static method and return only builder to set ids

2023-10-21 21:42 UTC, aidian3k commented on src/test/java/project/eepw/softwaretestingcrud/domain/user/data/UserServiceTest.java
> +    ThrowingCallable getUserByIdExecutable = () -> userService.getUserById(notExistingUserId);
It is not actually a callable but fine

2023-10-21 21:42 UTC, aidian3k commented on src/test/java/project/eepw/softwaretestingcrud/domain/user/data/UserServiceTest.java
> +    verify(userRepository).findById(notExistingUserId);
same here, what do we verify?

2023-10-22 08:28 UTC, briocky commented on src/test/java/project/eepw/softwaretestingcrud/domain/user/data/UserServiceTest.java
> +  }
Done

2023-10-22 19:45 UTC, aidian3k approved these changes

2023-10-22 20:00 UTC, merged